### ISSUE TITLE
redirectURI

### ISSUE THREAD

**Issue by mp1pro** [homathko/ca-jammming#2]
The convention for open source code is to save those credentials in another file called config.js and then import that file to pass in the variables. We would then add config.js to our .gitignore file so that it will not be added to github. Hence, when I clone this project and run, I would have to create my own config.js.

The redirectURI used is only based on your configuration. It would not matter to us.

**Comment by homathko** [comment]
Excellent. I do have questions, but I think I will just go ahead and implement this. Once I do, will you comment further on this issue please?

I suppose two questions I have off the bat are 1) Where is best practice to create the config.js file in my project file structure, and 2) how do I tell webpack to choose the appropriate redirectURL based on whether I run `npm start` or `npm run buid`?

**Comment by homathko** [comment]
Okay, please see commit `598e8e5`.

NM the questions!
